drop table if exists city
go

create table city
	(IdCity int primary key not null,
	CityName nvarchar(50) not null)

insert into city(IdCity,CityName) values
(1, N'Amsterdam'),
(2, N'Athens'),
(3, N'Barcelona'),
(4, N'Belfast'),
(5, N'Belgrade'),
(6, N'Berlin'),
(7, N'Bilbao'),
(8, N'Birmingham'),
(9, N'Bologna'),
(10, N'Bordeaux'),
(11, N'Brasov'),
(12, N'Bratislava'),
(13, N'Bristol'),
(14, N'Brno'),
(15, N'Brussels'),
(16, N'Bucharest'),
(17, N'Budapest'),
(18, N'Cardiff'),
(19, N'Cluj-Napoca'),
(20, N'Cologne'),
(21, N'Copenhagen'),
(22, N'Debrecen'),
(23, N'Dublin'),
(24, N'Dubrovnik'),
(25, N'Edinburgh'),
(26, N'Florence'),
(27, N'Frankfurt'),
(28, N'Gdansk'),
(29, N'Geneva'),
(30, N'Glasgow'),
(31, N'Gothenburg'),
(32, N'Graz'),
(33, N'Hamburg'),
(34, N'Helsinki'),
(35, N'Iași'),
(36, N'Innsbruck'),
(37, N'Istanbul'),
(38, N'Katowice'),
(39, N'Kiev'),
(40, N'Košice'),
(41, N'Krakow'),
(42, N'Leeds'),
(43, N'Lille'),
(44, N'Linz'),
(45, N'Lisbon'),
(46, N'Ljubljana'),
(47, N'London'),
(48, N'Lyon'),
(49, N'Madrid'),
(50, N'Manchester'),
(51, N'Marseille'),
(52, N'Milan'),
(53, N'Moscow'),
(54, N'Munich'),
(55, N'Nantes'),
(56, N'Naples'),
(57, N'Nice'),
(58, N'Nuremberg'),
(59, N'Osijek'),
(60, N'Oslo'),
(61, N'Ostrava'),
(62, N'Paris'),
(63, N'Pilsen'),
(64, N'Porto'),
(65, N'Prague'),
(66, N'Reykjavik'),
(67, N'Riga'),
(68, N'Rijeka'),
(69, N'Rome'),
(70, N'Rotterdam'),
(71, N'Salzburg'),
(72, N'Seville'),
(73, N'Sofia'),
(74, N'Stockholm'),
(75, N'Stuttgart'),
(76, N'Szeged'),
(77, N'Tallinn'),
(78, N'Timișoara'),
(79, N'Toulouse'),
(80, N'Turin'),
(81, N'Valencia'),
(82, N'Vienna'),
(83, N'Vilnius'),
(84, N'Warsaw'),
(85, N'Wrocław'),
(86, N'Zagreb'),
(87, N'Zurich')



