drop table if exists city
go

create table city
	(IdCity int primary key not null,
	CityName nvarchar(50) not null)

insert into city(IdCity,CityName) values
(1,N'Amsterdam'),
(2,N'Athens'),
(3,N'Barcelona'),
(4,N'Belfast'),
(5,N'Belgrade'),
(6,N'Berlin'),
(7,N'Berlin'),
(8,N'Bilbao'),
(9,N'Birmingham'),
(10,N'Bologna'),
(11,N'Bordeaux'),
(12,N'Brasov'),
(13,N'Bratislava'),
(14,N'Bristol'),
(15,N'Brno'),
(16,N'Brussels'),
(17,N'Bucharest'),
(18,N'Budapest'),
(19,N'Cardiff'),
(20,N'Cluj-Napoca'),
(21,N'Cologne'),
(22,N'Copenhagen'),
(23,N'Debrecen'),
(24,N'Dublin'),
(25,N'Dublin'),
(26,N'Dubrovnik'),
(27,N'Edinburgh'),
(28,N'Florence'),
(29,N'Frankfurt'),
(30,N'Gdansk'),
(31,N'Geneva'),
(32,N'Glasgow'),
(33,N'Glasgow'),
(34,N'Gothenburg'),
(35,N'Graz'),
(36,N'Hamburg'),
(37,N'Helsinki'),
(38,N'Iași'),
(39,N'Innsbruck'),
(40,N'Istanbul'),
(41,N'Katowice'),
(42,N'Kiev'),
(43,N'Košice'),
(44,N'Krakow'),
(45,N'Leeds'),
(46,N'Lille'),
(47,N'Linz'),
(48,N'Lisbon'),
(49,N'Ljubljana'),
(50,N'London'),
(51,N'Lyon'),
(52,N'Madrid'),
(53,N'Madrid'),
(54,N'Manchester'),
(55,N'Marseille'),
(56,N'Milan'),
(57,N'Moscow'),
(58,N'Munich'),
(59,N'Nantes'),
(60,N'Naples'),
(61,N'Nice'),
(62,N'Nuremberg'),
(63,N'Osijek'),
(64,N'Oslo'),
(65,N'Ostrava'),
(66,N'Paris'),
(67,N'Pilsen'),
(68,N'Porto'),
(69,N'Prague'),
(70,N'Reykjavik'),
(71,N'Riga'),
(72,N'Rijeka'),
(73,N'Rome'),
(74,N'Rotterdam'),
(75,N'Salzburg'),
(76,N'Seville'),
(77,N'Sofia'),
(78,N'Stockholm'),
(79,N'Stuttgart'),
(80,N'Szeged'),
(81,N'Tallinn'),
(82,N'Timișoara'),
(83,N'Toulouse'),
(84,N'Turin'),
(85,N'Valencia'),
(86,N'Vienna'),
(87,N'Vilnius'),
(88,N'Warsaw'),
(89,N'Wrocław'),
(90,N'Zagreb'),
(91,N'Zurich')



